local ReplicatedStorage = game:GetService("ReplicatedStorage")
local RunService = game:GetService("RunService")
local TweenService = game:GetService("TweenService")
local UserInputService = game:GetService("UserInputService")
local Superbullet = require(ReplicatedStorage.Packages.Superbullet)
local Signal = require(ReplicatedStorage.Packages.Signal)
local module = {}

local plr = game.Players.LocalPlayer
local mouse = plr:GetMouse()

---- Utilities


---- Superbullet Controllers

---- Superbullet Services


---- Datas


---- Assets

function module.Start()

end

function module.Init()

end

return module
